export enum InterpolationMethod {
  LAGRANGE = "LAGRANGE",
  NEWTON_DIVIDED_DIFFERENCES = "NEWTON_DIVIDED_DIFFERENCES",
  NEWTON_FINITE_DIFFERENCES = "NEWTON_FINITE_DIFFERENCES",
}

export enum PointInterpolationMethod {
  STIRLING = "STIRLING",
  BESSEL = "BESSEL",
}
